
export const INGREDIENT_SUBMITED = 'INGREDIENT_SUBMITED';
export const INGREDIENT_NOT_SUBMITED = 'INGREDIENT_NOT_SUBMITED';
export const DELETE_INGREDIENT = 'DELETE_INGREDIENT';
export const CHANGE_MEAL_NAME = 'CHANGE_MEAL_NAME';
export const CHANGE_INGREDIENT_PROP = 'CHANGE_INGREDIENT_PROP';
export const SEND_MEAL_TO_BACKEND = 'SEND_MEAL_TO_BACKEND';
