FROM postgres:14.1
RUN apt-get -y update
#RUN apt-get -y install vim

#
#ENV POSTGRES_PASSWORD="organizeit"
#ENV POSTGRES_USER="organizeit"
#ENV POSTGRES_DB="organizeit"
#
#
##VOLUME ommit that
#
#COPY onContainerStop app/onContainerStop
#RUN ["app/onContainerStop", "bg"]