spring:
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          google-login:
            provider: google
            client-id: 407066747704-s51j64j8lr7p9fjqigso5ca5c2a8ahr5.apps.googleusercontent.com
            client-secret: AV91UFmdvR-D1Ce1oUOivMmr
            scope: https://www.googleapis.com/auth/calendar