spring:
  datasource:
#    url: jdbc:h2:file:./data/demo
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      show-sql: true
  h2:
    console:
      enabled: true
      settings:
        web-admin-password: password