
## PostgreSQL
spring:
  sql:
    init:
      data-locations: classpath*:data-prod.sql
      mode: always

  datasource:
    url: jdbc:postgresql://localhost:8081/organizeit
    username: organizeit
    password: organizeit

  jpa:
    hibernate:
      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: true
#    properties:
#    show-sql: true
#        unique_constraint_strategy: RECREATE_QUIETLY
    defer-datasource-initialization: true



logging:
  level:
    org:
      hibernate:
        type: debug