spring:
  security:
    oauth2:
      client:
        registration:
          google-login:
            provider: google
            client-id: 407066747704-s51j64j8lr7p9fjqigso5ca5c2a8ahr5.apps.googleusercontent.com
            client-secret: NpWox85Xrjv5yd4o27hoc0m6